blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/giglium/vinted_scraper/discussions
    about: Use GitHub Discussions for questions and general help.
  - name: Security Vulnerabilities
    url: https://github.com/giglium/vinted_scraper/blob/main/SECURITY.md
    about: Please report security vulnerabilities following our security policy.
