---
name: Coverage

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: ["Test"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.workflow_run.conclusion == 'success'
    environment: coverage-reporting
    permissions:
      contents: read
      pull-requests: write

    env:
      HAS_CODECOV: ${{ secrets.CODECOV_TOKEN != '' }}
      HAS_CODACY: ${{ secrets.CODACY_PROJECT_TOKEN != '' }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup
        uses: "./.github/actions/setup-python"

      - name: Run Coverage
        run: make coverage

      - name: Upload coverage reports to Codecov
        if: ${{ env.HAS_CODECOV == 'true' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codacy
        if: ${{ env.HAS_CODACY == 'true' }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
          language: Python

      - name: Generate coverage comment
        if: ${{ github.event.workflow_run.event == 'pull_request' && env.HAS_CODECOV != 'true' && env.HAS_CODACY != 'true' }}
        uses: py-cov-action/python-coverage-comment-action@5d8df5979747514c914e1c5a12335a7cf9a2745f # v4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
