---
name: Quickstarts

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 9 * * 1" # Runs every Monday at 9:00 AM UTC

permissions: read-all

jobs:
  test_quickstarts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v6 # zizmor: ignore[unpinned-uses]
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6 # zizmor: ignore[unpinned-uses]
        with:
          version: "0.8.9"
          enable-cache: true

      - name: Run the async wrapper quickstart
        run: uv run -m examples.async_wrapper

      - name: Run the async scraper quickstart
        run: uv run -m examples.async_scraper

      - name: Run the wrapper quickstart
        run: uv run -m examples.wrapper

      - name: Run the scraper quickstart
        run: uv run -m examples.scraper
