---
name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test_python_version:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run tests
        run: make test

  test_old_python_version:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.6'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      # Data Classes (https://peps.python.org/pep-0557/) was introduced in python 3.7
      # To work around it, I need to install it with pip
      - name: Install dataclasses
        run: python -m pip install dataclasses

      - name: Run tests
        run: make test